source ~/.zsh/checks.zsh
#source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
#source ~/.zsh/exports.zsh
#source ~/.zsh/prompt.zsh
#source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
#source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
source ~/.zsh/zsh_hooks.zsh


# Set architecture flags
export ARCHFLAGS="-arch x86_64"

# Customize to your needs...
export PATH=/usr/local/share/python:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
export EDITOR="/usr/local/bin/mate -w"

# Location of your virtualenv files
export WORKON_HOME=$HOME/.virtualenvs
# Location of your project working directories
export PROJECT_HOME=$HOME/labs/python
# virtualenv should use Distribute instead of legacy setuptools
export VIRTUALENV_DISTRIBUTE=true
# Centralized location for new virtual environments
export PIP_VIRTUALENV_BASE=$WORKON_HOME
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
# pass default argument to skip using computer wide packages
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages'

# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ANTIGEN=$HOME/labs/misc/antigen

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="agnoster"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

source $ANTIGEN/antigen.zsh

# Load the oh-my-zsh's library.
antigen-lib

# Bundles from the default repo declared above.
antigen-bundles <<EOBUNDLES

pip
virtualenvwrapper

npm

# Guess what to install when running an unknown command.
command-not-found

# Helper for extracting different types of archives.
extract

# Help working with version control systems.
git

# nicoulaj's moar completion files for zsh
zsh-users/zsh-completions src

# ZSH port of Fish shell's history search feature.
zsh-users/zsh-history-substring-search

# Syntax highlighting bundle.
zsh-users/zsh-syntax-highlighting

# autoenv adjusted for zsh
sharat87/autoenv

EOBUNDLES

# Tracks your most used directories, based on 'frecency'. And its accompanying
# setup code.
antigen-bundle rupa/z
add-zsh-hook precmd _z_precmd
function _z_precmd {
    _z --add "$PWD"
}

function syspip {
   PIP_REQUIRE_VIRTUALENV="" pip "$@"
}

# Load the theme.
antigen-theme agnoster

antigen apply


